// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lvefgadeywiktazmukgk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2ZWZnYWRleXdpa3Rhem11a2drIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyODQ0NjEsImV4cCI6MjA2Njg2MDQ2MX0.6Dy42zU9S9xuG7Ntj2WV16pvIgpCPwzSqfk9HSM1fYg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});